sudo: required
services:
- docker
env:
  global:
    - GIT_SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - DOCKERID=hypy

before_install:
- docker build -t $DOCKERID/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run $DOCKERID/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
